<?php

use Illuminate\Database\Seeder;

class KeywordTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $keywords = [
            'nike',
            'reebok',
            'adidas',
            'tom ford',
            'brooks',
            'saucony',
            'toms',
            'puma',
            'keds',
            'lugz',
            'asics',
            'montrail',
            'merrell',
            'steve madden',
            'dc',
            'dvs',
            'etnies',
            'rockport',
            'vans',
            'nike shoes',
            'nike shoe',
            'reebok shoes',
            'reebok shoe',
            'adidas shoes',
            'adidas shoe',
            'tom ford shoes',
            'tom ford shoe',
            'brooks shoes',
            'brooks shoe',
            'saucony shoes',
            'saucony shoe',
            'toms shoes',
            'toms shoe',
            'puma shoes',
            'puma shoe',
            'keds shoes',
            'keds shoe',
            'lugz shoes',
            'lugz shoe',
            'asics shoes',
            'asics shoe',
            'montrail shoes',
            'montrail shoe',
            'merrell shoes',
            'merrell shoe',
            'steve madden shoes',
            'steve madden shoe',
            'dc shoes',
            'dc shoe',
            'dvs shoes',
            'dvs shoe',
            'etnies shoes',
            'etnies shoe',
            'rockport shoes',
            'rockport shoe',
            'vans shoes',
            'vans shoe',
            'blue Nike',
            'black Nike',
            'red Nike',
            'Nike Air Max 1',
            'Nike x sacai Dunk Lux',
            'Nike Romaleos 2',
            'Nike Free Trainer 1.0',
            'Nike Air Zoom Pegasus',
            'Nike Pro Stepper',
            'Nike Free 5.0',
            'Nike Kobe X',
            'Nike Kobe',
            'Nike Lebron',
            'Nike Blazer',
            'Nike Kyrie',
            'Nike Zoom Speed Trainer',
            'Nike Zoom Rival',
            'Nike Zoom',
            'blue Nike Air Max 1',
            'blue Nike x sacai Dunk Lux',
            'blue Nike Romaleos 2',
            'blue Nike Free Trainer 1.0',
            'blue Nike Air Zoom Pegasus',
            'blue Nike Pro Stepper',
            'blue Nike Free 5.0',
            'blue Nike Kobe X',
            'blue Nike Kobe',
            'blue Nike Lebron',
            'blue Nike Blazer',
            'blue Nike Kyrie',
            'blue Nike Zoom Speed Trainer',
            'blue Nike Zoom Rival',
            'blue Nike Zoom',
            'black Nike Air Max 1',
            'black Nike x sacai Dunk Lux',
            'black Nike Romaleos 2',
            'black Nike Free Trainer 1.0',
            'black Nike Air Zoom Pegasus',
            'black Nike Pro Stepper',
            'black Nike Free 5.0',
            'black Nike Kobe X',
            'black Nike Kobe',
            'black Nike Lebron',
            'black Nike Blazer',
            'black Nike Kyrie',
            'black Nike Zoom Speed Trainer',
            'black Nike Zoom Rival',
            'black Nike Zoom',
            'red Nike Air Max 1',
            'red Nike x sacai Dunk Lux',
            'red Nike Romaleos 2',
            'red Nike Free Trainer 1.0',
            'red Nike Air Zoom Pegasus',
            'red Nike Pro Stepper',
            'red Nike Free 5.0',
            'red Nike Kobe X',
            'red Nike Kobe',
            'red Nike Lebron',
            'red Nike Blazer',
            'red Nike Kyrie',
            'red Nike Zoom Speed Trainer',
            'red Nike Zoom Rival',
            'red Nike Zoom',
        ];

        $keyword_group = \App\Keywordgroup::first();
        foreach($keywords as $keyword)
        {
            $keyword_group->keywords()->create(['name' => $keyword]);
        }

    }
}
